/*CREATE DATABASE BIBLIONLINE;*/

CREATE TABLE LIVRO(
	ISBN INT(13)UNIQUE NOT NULL,
        TITULO VARCHAR(50) NOT NULL,
        SUBTITULO VARCHAR(40) DEFAULT NULL,
        AUTOR VARCHAR(50) NOT NULL,
        EDITORA VARCHAR(30) NOT NULL,
        ANO_PUBLICACAO INT(5),
        QUANTIDADE INT NOT NULL,
        TAG VARCHAR (40),
        TIPO VARCHAR (13) NOT NULL,
        GENERO VARCHAR (15) DEFAULT NULL,
        PRIMARY KEY(ISBN),
        CHECK(TIPO = 'Didático' OR TIPO = 'Paradidático' OR TIPO = 'Romance')
);

CREATE TABLE USUARIO(
	CPF INT (11) UNIQUE NOT NULL,
        NOME VARCHAR (50) NOT NULL,
        NICKNAME VARCHAR (30) NOT NULL,
        EMAIL VARCHAR (30) DEFAULT NULL,
        TELEFONE INT (12) NOT NULL,
        TIPO VARCHAR (12) NOT NULL,
        RUA VARCHAR (40) NOT NULL,
        BAIRRO VARCHAR (30) NOT NULL,
        NUMERO VARCHAR (7) NOT NULL,
        COMPLEMENTO VARCHAR (30) DEFAULT NULL,
        CEP INT (8) NOT NULL,
        PRIMARY KEY(CPF),
        CHECK(TIPO = 'funcionário' OR TIPO = 'usuário')
);

CREATE TABLE LOCACAO(
	ISBN INT (13) NOT NULL,
        CPF_USUARIO INT (11) NOT NULL,
        CPF_FUNCIONARIO INT (11) NOT NULL,
        DATA_RETIRADA DATETIME NOT NULL,
        DATA_DEVOLUCAO DATETIME NOT NULL,
        PRIMARY KEY(ISBN, DATA_RETIRADA),
        FOREIGN KEY(ISBN) REFERENCES LIVRO(ISBN),
        FOREIGN KEY(CPF_USUARIO) REFERENCES USUARIO(CPF),
        FOREIGN KEY(CPF_FUNCIONARIO)REFERENCES USUARIO(CPF)
);

CREATE TABLE RESERVA(
        ISBN INT (13) NOT NULL,
        CPF INT (11) NOT NULL,
        DATA_RESERVA DATETIME NOT NULL,
        DATA_RETIRADA DATETIME NOT NULL,
        PRIMARY KEY(ISBN, CPF),
        FOREIGN KEY(ISBN) REFERENCES LIVRO(ISBN),
        FOREIGN KEY(CPF) REFERENCES USUARIO(CPF)
);

CREATE TABLE DEVOLUCAO(
	ISBN INT (13) NOT NULL,
        CPF_FUNCIONARIO INT (11) NOT NULL,
        CPF_USUARIO INT (11) NOT NULL,
        DATA_DEVOLUCAO DATETIME NOT NULL,
        PRIMARY KEY(ISBN, DATA_DEVOLUCAO),
        FOREIGN KEY(ISBN) REFERENCES LIVRO(ISBN),
        FOREIGN KEY(CPF_USUARIO) REFERENCES USUARIO(CPF),
        FOREIGN KEY(CPF_FUNCIONARIO)REFERENCES USUARIO(CPF)
);
        
        